### ISSUE TITLE
Can't generate Footprints

### ISSUE THREAD

**Issue by frazucca** [UCANR-IGIS/uasimg#10]
Hi,
despite the **uas_info** appears correctly recognize  the DRONE camera, and the **uas_report**  produce a good report (with camera center points), by using  _uas_exp_shp(flight1, fp=TRUE)_
I get the following msg
_**Footprints not found. Skipping.**_

Same msg from 
 _uas_worldfile(flight1, aux.xml = TRUE, wld = TRUE)_
Done.
Warning message:
**_Can not generate world file(s). . does not have footprints._**

Any hints?
TIA

Best
franz

**Comment by ajlyons** [comment]
Try running `uas_info()` again, this time with `fp=TRUE` (the default is FALSE) and `update_cache = TRUE` (at least the first time you re-run it). 

Modelled footprints are saved in the 'flight info' object returned by `uas_info()`, so if they aren't computed when you run that function you can't use them subsequently. In an upcoming update, the warning messages about 'footprints not found' will be make this clearer.

**Comment by frazucca** [comment]
Done it.
Great!!

thank you
fz
