### ISSUE TITLE
How change measure units in report?

### ISSUE THREAD

**Issue by frazucca** [UCANR-IGIS/uasimg#11]
Hi
It's possible to change the report (_**uas_report**_) measure units from _acres,ft & inch_ to  _sqkm, meters and cm_?

TIA
Best
fz

**Comment by ajlyons** [comment]
Great idea - thanks. This is now supported by the new `units` argument in `uas_report()` in version 1.9.0. When `units = 'metric'`, units for the flight area, above-launch altitude, and GSD will be reported in hectares, m, and cm respectively.
