### ISSUE TITLE
Hi-phen Airphen multispectral camera

### ISSUE THREAD

**Issue by mmbaye** [UCANR-IGIS/uasimg#2]
Please,  include  Hi-phen Airphen multispectral camera  in the list of supported sensors?
thanks

**Comment by ajlyons** [comment]
Thanks, this is a good idea. I'm not familiar with the [Airphen](https://applied-infrared.com.au/images/pdf/Airphen.pdf) sensor and don't have a sample to test. Would you be able to share an image or two, so that I can look at the EXIF data?

**Comment by mmbaye** [comment]
Dear Andy ,
Please see attached the an Airphen
Thanks so much
modou

**Comment by ajlyons** [comment]
The Hi-phen Airphen was added to the camera database in v1.7.7. Let me know if there are any follow-up issues.

**Comment by mmbaye** [comment]
HI   wooww. Great  I will check it.

Modou

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
