### ISSUE TITLE
Add DJI Zenmuse L1 camera to the database...

### ISSUE THREAD

**Issue by tripplowe** [UCANR-IGIS/uasimg#3]
Can you add the DJI Zenmuse L1 camera to the database?  I think the integrated camera is very similar to the Phantom 4 camera ( https://www.dji.com/zenmuse-l1/specs )

**Comment by tripplowe** [comment]
Ah, it was easy enough to edit the cameras.csv myself...

**Comment by ajlyons** [comment]
Thanks @tripplowe, glad you were able to edit the cameras.csv file successfully. If you're willing to share the camera parameters you entered, I can add them to the cameras.csv file that ships with the package so others can use them as well. And/or a sample photo from this camera.

**Comment by ajlyons** [comment]
I haven't been able to find the sensor dimensions for this camera, and it isn't in the Pix4Dmapper camera database which is my go-to resource for camera specs. I also haven't been able to find any sample RGB images from the Zenmuse L1 for testing purposes. If anyone is still interested in having this camera included in uasimg and has some of this info, please let me know. 

Also note that even though we don't have the specs for this camera, you should still be able to make maps of the locations where L1 images were taken. As of v1.7.7 (2021-09-15), if the camera type isn't known it should still be able to extract the coordinates of the images, so you can make data catalogs. The only thing you can't do without camera parameters is compute the estimated footprints.
