### ISSUE TITLE
Add P4 RTK camera to the database please

### ISSUE THREAD

**Issue by RobinCurtis** [UCANR-IGIS/uasimg#4]
Hi,
Any chance you could add the P4 RTK camera to the database please?
https://www.dji.com/uk/phantom-4-rtk/info
Many thanks
Robin

**Comment by ajlyons** [comment]
Absolutely. Would you be able to share a photo (or link to a photo) from this camera to make sure I enter the EXIF tags correct?

**Comment by RobinCurtis** [comment]
Thats brilliant Andy thanks so much! BTW I'm testing more drones this month so expect a couple of other requests eg P4 multispectral! :-)
I attach image from P4 RTK
![100_0002_0128](https://user-images.githubusercontent.com/73179484/156427345-10c7efcd-8cc5-433c-98b7-827a8a85b9f9.JPG)

**Comment by RobinCurtis** [comment]
Hi Andy,
I just wondered if you managed to add imagery that I uploaded from the P4 RTK to your database?
I also want to add images from a sensefly ebee.
Can Ido this myself or do you have to do it?
Many thanks,
Robin
________________________________

**Comment by ajlyons** [comment]
Hi Robin, sorry this took a while but I added the P4 RTK and P4 MS to the camera database in version v1.8.0. They seem to work fine with some sample images but check it out and let me know if they work. Note that images from the P4 MS do not record the relative altitude above launch (common for multispectral cameras), so you can't model on-the-ground footprints for those images unless you manually pass the AGL altitude as an argument to `uas_info()`. 

You can certainly add additional cameras yourself by modifying the csv file that comes with the package (or making a copy of it and passing the filename as the cameras argument in `uas_info`). I flushed out the help page for `uas_cameras()` a bit to explain this. If you share the camera settings I'll be happy to add them to the cameras.csv (or do a pull request) so others can benefit from them as well.

**Comment by RobinCurtis** [comment]
Hi Andy,
That is great - thanks very much.
I did give it a try and as you said in the report it says
EXIF Data Analysis

Estimates of ground sampling distance, above ground elevation, and footprints not available.


So to rectify this I would have to pass the AGL as an argument manually for each of the images? Is that correct? There are quite a few images so this would take quite a bit of work...

Anyhow many thanks for adding my cameras.

Best wishes,

Robin

________________________________
